"""Identifier generation utilities.

Generates IDs that are lexicographically sortable by creation time.
Format: {prefix}_{hex_timestamp}{random_base62}

The timestamp portion uses 8 bytes (64 bits) encoded as 16 hex chars,
combining ``timestamp_ms * 0x1000 + counter`` (fixes C1: float truncation
and 48-bit overflow for 2025+ timestamps).
"""

from __future__ import annotations

import secrets
from typing import Literal

from wolfharness.utils.time_utils import now_ms


PrefixType = Literal["session", "message", "permission", "user", "part", "pty", "call"]

PREFIXES: dict[PrefixType, str] = {
    "session": "ses",
    "message": "msg",
    "permission": "per",
    "user": "usr",
    "part": "prt",
    "pty": "pty",
    "call": "cal",
}

BASE62_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
ID_LENGTH = 30  # Characters after prefix (16 hex + 14 base62)
HEX_LENGTH = 16  # Hex timestamp portion (8 bytes encoded as 16 hex chars)
_MIN_ID_PARTS = 2  # Prefix + payload, separated by "_"

# State for monotonic ID generation
_last_timestamp = 0
_counter = 0


def _random_base62(length: int) -> str:
    """Generate random base62 string."""
    return "".join(secrets.choice(BASE62_CHARS) for _ in range(length))


def ascending(prefix: PrefixType, given: str | None = None) -> str:
    """Generate an ascending (chronologically sortable) ID.

    Args:
        prefix: The type prefix for the ID
        given: If provided, validate and return this ID instead of generating

    Returns:
        A sortable ID with the format {prefix}_{hex_timestamp}{random}

    Raises:
        ValueError: If given ID doesn't start with expected prefix
    """
    if given is not None:
        expected_prefix = PREFIXES[prefix]
        if not given.startswith(expected_prefix):
            msg = f"ID {given} does not start with {expected_prefix}"
            raise ValueError(msg)
        return given

    return _create(prefix, descending=False)


def descending(prefix: PrefixType) -> str:
    """Generate a descending (reverse chronologically sortable) ID.

    Args:
        prefix: The type prefix for the ID

    Returns:
        A reverse-sortable ID
    """
    return _create(prefix, descending=True)


def _create(prefix: PrefixType, *, descending: bool = False) -> str:
    """Create a new ID with timestamp encoding.

    Args:
        prefix: The type prefix
        descending: If True, invert the timestamp for reverse sorting

    Returns:
        A new ID string
    """
    global _last_timestamp, _counter  # noqa: PLW0603

    current_timestamp = now_ms()  # milliseconds, integer (no float truncation)

    if current_timestamp > _last_timestamp:
        # Clock advanced normally — reset counter for new millisecond.
        _last_timestamp = current_timestamp
        _counter = 0
    elif current_timestamp < _last_timestamp:
        # Clock went backward (NTP adjustment, leap second, etc.).
        # Keep the last timestamp and continue incrementing the counter
        # so IDs remain monotonically increasing despite the clock jump.
        # The counter has 12 bits (0x1000 = 4096 values per ms), which
        # is enough for ~4096 IDs per ms — far exceeding typical usage.
        pass
    # If equal, same millisecond — counter increments naturally.

    _counter += 1

    # If counter overflows 12 bits (4096 IDs in one ms), bump timestamp.
    counter_max = 0xFFF
    if _counter > counter_max:
        _last_timestamp += 1
        _counter = 1

    # Combine timestamp and counter
    now = _last_timestamp * 0x1000 + _counter

    if descending:
        now = ~now & 0xFFFFFFFFFFFFFFFF  # Invert for descending order (64 bits)

    # Encode as 8 bytes (64 bits), big-endian
    time_bytes = now.to_bytes(8, "big")

    time_hex = time_bytes.hex()

    # Add random suffix (14 chars for 30 total after prefix)
    random_suffix = _random_base62(ID_LENGTH - 16)

    return f"{PREFIXES[prefix]}_{time_hex}{random_suffix}"


def generate_session_id() -> str:
    """Generate a unique, reverse-chronologically sortable session ID.

    Uses ``descending()`` to match OpenCode's ``SessionID.create()``
    convention: newer sessions have lexicographically smaller IDs.

    Returns:
        A session ID like 'ses_fffff9ceaec006feZHcn6VSpkaBcHi'
    """
    return descending("session")


def extract_timestamp_ms(identifier: str) -> int | None:
    """Extract the millisecond timestamp embedded in an ascending/descending ID.

    The ID format is ``{prefix}_{16 hex chars}{14 base62 chars}``.
    The hex portion encodes ``timestamp_ms * 0x1000 + counter`` (ascending)
    or its bitwise NOT (descending).

    Args:
        identifier: An ID string generated by ``ascending()`` or ``descending()``.

    Returns:
        The epoch millisecond timestamp, or ``None`` if the ID format is
        unrecognized (e.g. UUID or custom format).
    """
    parts = identifier.split("_", 1)
    if len(parts) != _MIN_ID_PARTS or len(parts[1]) < HEX_LENGTH:
        return None
    prefix = parts[0]
    if prefix not in PREFIXES.values():
        return None
    hex_part = parts[1][:16]
    try:
        value = int(hex_part, 16)
    except ValueError:
        return None
    # Descending IDs have the high bit set (bitwise NOT of a small timestamp).
    if value & 0x8000000000000000:
        value = ~value & 0xFFFFFFFFFFFFFFFF
    return value >> 12
