# yaml-language-server: $schema=https://raw.githubusercontent.com/phil65/wolfharness/refs/heads/main/schema/config-schema.json
prompts:
  system_prompts:
    word_chain:
      category: role
      content: |
        "Append one word to the given word or sentence and continue the sentence indenfinitely."

agents:
  player1:
    type: native
    model: openai:gpt-5-mini
    system_prompt:
      - type: library
        reference: word_chain
    connections:
      - type: node
        name: player2
        connection_type: run

  player2:
    type: native
    model: openai:gpt-5-mini
    system_prompt:
      - type: library
        reference: word_chain
    connections:
      - type: node
        name: player3
        connection_type: run
        stop_condition:
          type: cost_limit
          max_cost: 0.01 # stop circle when this agent reaches 0.01 cost

  player3:
    type: native
    model: openai:gpt-5-mini
    system_prompt:
      - type: library
        reference: word_chain
    connections:
      - type: node
        name: player1
        connection_type: run
