"""HostContext — frozen dataclass capturing AgentPool infrastructure fields.

This is the Wave 1 foundation for the host layer. It maps existing
AgentPool fields into an immutable context object that downstream
factory and registry layers will consume.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from wolfharness.host.stubs import CapabilityCache, ModelCache, ModelRegistry


if TYPE_CHECKING:
    from pathlib import Path

    from anyenv import ProcessManager
    from upathtools import UPath

    from wolfharness.capabilities.extension_registry import ExtensionRegistry
    from wolfharness.mcp_server.manager import MCPManager
    from wolfharness.models.manifest import AgentsManifest
    from wolfharness.orchestrator import SessionPool
    from wolfharness.prompts.manager import PromptManager
    from wolfharness.skills.manager import SkillsManager
    from wolfharness.storage import StorageManager
    from wolfharness.talk.registry import ConnectionRegistry
    from wolfharness.utils.streams import FileOpsTracker
    from wolfharness.utils.todos import TodoTracker
    from wolfharness.vfs_registry import VFSRegistry


@dataclass(frozen=True)
class RunScope:
    """Immutable scope identifying a single run within the host.

    Captures the configuration, tenant, user, and session context for
    a run. The ``session_id`` is auto-generated by RunLoop in M2;
    an empty string serves as placeholder until then.

    Attributes:
        config_id: Configuration identifier (defaults to "default").
        tenant_id: Tenant identifier for multi-tenant isolation.
        user_id: User identifier for the run owner.
        session_id: Session identifier, auto-generated by RunLoop in M2.
    """

    config_id: str = "default"
    tenant_id: str = "default"
    user_id: str = "anonymous"
    session_id: str = ""


@dataclass(frozen=True)
class HostContext:
    """Immutable snapshot of AgentPool infrastructure.

    Captures all shared services from an AgentPool instance so that
    agent factory and registry layers can receive a single typed
    context instead of the full pool object.
    """

    manifest: AgentsManifest
    storage: StorageManager
    vfs_registry: VFSRegistry
    connection_registry: ConnectionRegistry
    mcp: MCPManager
    skills_registry: SkillsManager
    prompt_manager: PromptManager
    process_manager: ProcessManager
    file_ops: FileOpsTracker
    todos: TodoTracker
    session_pool: SessionPool | None
    config_file_path: str | Path | UPath | None
    config_id: str | None = None
    tenant_id: str | None = None
    capability_cache: CapabilityCache = field(default_factory=CapabilityCache)
    model_registry: ModelRegistry = field(default_factory=ModelRegistry)
    model_cache: ModelCache = field(default_factory=ModelCache)
    main_agent_name: str | None = None
    extension_registry: ExtensionRegistry | None = None
