"""DCP state and compression block dataclasses.

Defines the per-session state that the Dynamic Context Pruning capability
maintains and the action/block records created during pruning operations.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import IntEnum
from typing import TYPE_CHECKING, Any, ClassVar, Literal


if TYPE_CHECKING:
    from pydantic_ai.messages import ModelMessage

    from wolfharness.capabilities.dcp.block_store import CompressionBlockStore


class WatermarkLevel(IntEnum):
    """Context pressure watermark levels for escalation.

    Levels increase monotonically so ``>=`` comparisons work natively.
    """

    NORMAL = 0
    INFO = 1
    WARNING = 2
    CRITICAL = 3


@dataclass
class DistillTarget:
    """A single distillation target for a ``distill`` action.

    Attributes:
        tool_call_id: The tool call ID to distill.
        distillation: The distilled summary text replacing the original output.
    """

    tool_call_id: str
    distillation: str


@dataclass
class PruneAction:
    """A pending pruning action generated by a strategy.

    Stores the decision parameters so the action can be deferred and applied
    together with others in a batch.

    Attributes:
        kind: The type of pruning action to perform.
        ids: Tool call IDs to prune (for ``prune`` kind).
        targets: Distillation targets (for ``distill`` kind).
        summary: Optional summary text (for ``distill``).
        start_string: Optional sentinel marking the start of a range.
        end_string: Optional sentinel marking the end of a range.
        source_tool_call_id: The tool call ID that generated this action.
    """

    kind: Literal["prune", "distill"]
    ids: tuple[str, ...] = ()
    targets: tuple[DistillTarget, ...] = ()
    summary: str = ""
    start_string: str = ""
    end_string: str = ""
    source_tool_call_id: str = ""


@dataclass
class CompressionBlock:
    """A compression block recording what was compressed and how.

    Together with ``CompressionBlockStore`` these form an append-only log
    of all structural and semantic compression operations.

    Attributes:
        block_id: Unique identifier for this block.
        original_tool_call_ids: The tool call IDs that were replaced.
        compressed_content: The compressed representation.
        kind: The compression strategy used.
        parent_block_id: For nested blocks — the encompassing block's ID.
        timestamp: When this block was created.
    """

    _VALID_KINDS: ClassVar[tuple[str, ...]] = ("prune", "distill", "dedup")

    block_id: str
    original_tool_call_ids: tuple[str, ...]
    compressed_content: str
    kind: Literal["prune", "distill", "dedup"]
    parent_block_id: str | None = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    def __post_init__(self) -> None:
        """Validate that ``kind`` is one of the allowed values.

        ``Literal`` is a type-hint-only construct; runtime enforcement ensures
        removed kinds (e.g. ``compress``) are rejected at construction time.
        """
        if self.kind not in self._VALID_KINDS:
            msg = f"Invalid kind {self.kind!r}. Must be one of {self._VALID_KINDS}."
            raise TypeError(msg)


@dataclass
class DCPState:
    """Per-session state for the Dynamic Context Pruning capability.

    Tracks pending actions, applied pruning decisions, watermark escalation,
    and the compression block store reference.

    Attributes:
        pending_actions: Queue of pruning actions yet to be applied.
        applied_action_ids: Set of action IDs that have been applied.
        pruned_tool_ids: tool_call_ids pruned/distilled, re-applied each iteration.
        distill_texts: Distillation text per tool_call_id (for distill actions).
        current_turn: The current conversation turn number.
        step_count: Number of tool-call steps in the current turn.
        tool_id_list: Mapping of sequence numbers to tool call IDs.
        nudge_counter: Counter for turn-based nudge injection tracking.
        nudge_step_counter: Counter for step-based nudge injection tracking.
        nudges: Mapping of anchor names to whether a nudge was injected.
        watermark_level: Current context pressure watermark level.
        current_tokens: Estimated token count for the current context.
        block_store: Reference to the ``CompressionBlockStore`` instance.
        current_messages: Snapshot of current messages for tool scanning.
    """

    pending_actions: deque[PruneAction] = field(default_factory=deque)
    applied_action_ids: set[str] = field(default_factory=set)
    # tool_call_ids that have been pruned or distilled, persisted across iterations
    # so pruning can be re-applied every before_model_request (ctx.state.message_history
    # retains original content; our modifications to request_context.messages are ephemeral).
    pruned_tool_ids: set[str] = field(default_factory=set)
    # Distillation texts for distill actions, keyed by tool_call_id.
    distill_texts: dict[str, str] = field(default_factory=dict)
    current_turn: int = 0
    step_count: int = 0
    tool_id_list: list[str] = field(default_factory=list)
    nudge_counter: int = 0
    nudge_step_counter: int = 0
    current_messages: list[ModelMessage] | None = None
    block_store: CompressionBlockStore | None = None
    nudges: dict[str, bool] = field(default_factory=dict)
    watermark_level: WatermarkLevel = WatermarkLevel.NORMAL
    current_tokens: int = 0
    # Token tracking: use API-reported real token counts (ctx.usage.input_tokens)
    # as the base for watermark, and estimate_tokens for only the incremental
    # messages added since the last pipeline run. This avoids compounding
    # estimate error from system prompt + tool schemas + API format overhead.
    last_cumulative_input_tokens: int = 0
    # Number of messages in request_context at the start of the last
    # before_model_request. Used to compute the delta (new messages since last
    # pipeline run) for incremental token estimation.
    last_pipeline_msg_count: int = 0
    # Persistent flag: when True, ThinkingPart content is stripped from
    # assistant messages before the last user message on every pipeline run.
    # Toggled by the model via prune(clear_thinking=True/False).
    clear_thinking_active: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DCPState:
        """Reconstruct from a JSON/plain-dict, e.g. after a SQL JSON column roundtrip.

        ``block_store`` and ``current_messages`` are runtime-only references
        that cannot survive serialization — they default to ``None``.
        """
        state = cls()
        if "pending_actions" in data:
            actions: list[PruneAction] = []
            for item in data["pending_actions"]:
                if not isinstance(item, dict):
                    actions.extend(item)  # already a PruneAction
                    continue
                kind = item.get("kind", "prune")
                ids = tuple(item.get("ids", ()))
                targets = tuple(
                    DistillTarget(**t) if isinstance(t, dict) else t
                    for t in item.get("targets", ())
                )
                actions.append(
                    PruneAction(
                        kind=kind,
                        ids=ids,
                        targets=targets,
                        summary=item.get("summary", ""),
                        start_string=item.get("start_string", ""),
                        end_string=item.get("end_string", ""),
                        source_tool_call_id=item.get("source_tool_call_id", ""),
                    ),
                )
            state.pending_actions = deque(actions)
        for _set_field in ("applied_action_ids", "pruned_tool_ids"):
            if _set_field in data and isinstance(data[_set_field], (list, set)):
                setattr(state, _set_field, set(data[_set_field]))
        if "distill_texts" in data:
            state.distill_texts = dict(data["distill_texts"])
        if "tool_id_list" in data:
            state.tool_id_list = list(data["tool_id_list"])
        if "nudges" in data:
            state.nudges = dict(data["nudges"])
        if "watermark_level" in data:
            wl = data["watermark_level"]
            state.watermark_level = WatermarkLevel(wl) if isinstance(wl, int) else wl
        for int_field in (
            "current_turn",
            "step_count",
            "nudge_counter",
            "nudge_step_counter",
            "current_tokens",
            "last_cumulative_input_tokens",
            "last_pipeline_msg_count",
        ):
            if int_field in data:
                setattr(state, int_field, int(data[int_field]))
        if "clear_thinking_active" in data:
            state.clear_thinking_active = bool(data["clear_thinking_active"])
        return state
